import type { Service } from './data';

export const services: Service[] = [
  {
    title: 'UI/UX Design',
    shortBio: 'Modern, user-focused mobile app and website design with seamless usability.',
    price: '₹10,000 (full project)',
    icon: "🎨",
    tool: "Figma",
    bgColor: "bg-blue-100",
    whatIProvide: [
      'Mobile app design',
      'Website UI design',
      'Prototyping and wireframes',
      'Responsive layouts',
      'Design system creation',
    ],
    tags: ['UI Design', 'UX Design', 'Mobile Apps', 'Websites', 'Prototypes', 'Wireframes'],
    whyWorkWithMe: [
      'User-first approach',
      'Fast turnaround',
      'Modern, trend-aligned designs',
      'Proven track record with startups and businesses',
      'Clear communication',
    ],
  },
  {
    title: 'UX Strategy',
    shortBio: 'Research, redesign, and consulting to improve product usability and conversions.',
    price: 'Custom pricing',
    icon: "✏️",
    tool: "Research",
    bgColor: "bg-yellow-100",
    whatIProvide: [
      'UX audits & usability testing',
      'Customer journey mapping',
      'Redesign recommendations',
      'Conversion rate optimization',
      'Accessibility improvements',
    ],
    tags: ['UX Research', 'Usability', 'CRO', 'User Testing', 'Redesign', 'Strategy'],
    whyWorkWithMe: [
      'Data-driven decision-making',
      'Industry-proven UX methods',
      'Tailored strategies for your target audience',
      'Long-term growth focus',
      'Hands-on collaboration',
    ],
  },
  {
    title: 'SEO & Marketing',
    shortBio: 'Creative SEO and digital marketing for strong online presence.',
    price: 'Custom pricing',
    icon: "📈",
    tool: "Marketing",
    bgColor: "bg-purple-100",
    whatIProvide: [
      'On-page & technical SEO',
      'Keyword research',
      'Blog & content optimization',
      'Social media strategy',
      'Ad campaign setup & optimization',
    ],
    tags: ['SEO', 'Digital Marketing', 'Keywords', 'Google Ads', 'Social Media', 'Content Marketing'],
    whyWorkWithMe: [
      'White-hat SEO practices',
      'Measurable marketing results',
      'Custom strategies for your niche',
      'Latest marketing tools & trends',
      'End-to-end digital growth approach',
    ],
  },
  {
    title: 'AI Web Development',
    shortBio: 'Websites from scratch with AI-powered speed and functionality.',
    price: '₹1k–₹5k',
    icon: "✨",
    tool: "Webflow",
    bgColor: "bg-pink-100",
    whatIProvide: [
      'AI-assisted website creation',
      'Landing page development',
      'API integration',
      'Speed optimization',
      'CMS setup (WordPress, custom, etc.)',
    ],
    tags: ['AI Web Dev', 'Landing Pages', 'API Integration', 'Website Speed', 'CMS', 'Automation'],
    whyWorkWithMe: [
      'Faster delivery with AI tools',
      'Clean, modern coding standards',
      'Fully responsive & SEO-ready',
      'Easy-to-manage backend',
      'Affordable pricing for startups',
    ],
  },
  {
    title: 'Content & Branding',
    shortBio: 'AI-assisted content creation to strengthen brand and engage audiences.',
    price: 'Per content',
    icon: '✍️',
    tool: 'Content',
    bgColor: 'bg-green-100',
    whatIProvide: [
      'Brand voice & identity setup',
      'AI-generated blog & article writing',
      'Social media content creation',
      'Copywriting for ads & websites',
      'Content calendar planning',
    ],
    tags: ['Content Writing', 'Branding', 'Copywriting', 'Social Media', 'Marketing', 'AI Content'],
    whyWorkWithMe: [
      'Creative storytelling with AI precision',
      'Consistent, brand-aligned content',
      'Engaging and SEO-optimized writing',
      'Experienced in multiple industries',
      'On-time content delivery',
    ],
  },
  {
    title: 'E-Commerce Solutions',
    shortBio: 'Shopify stores with admin, SEO, marketing, and sales optimization.',
    price: 'Custom pricing',
    icon: '🛒',
    tool: 'Shopify',
    bgColor: 'bg-orange-100',
    whatIProvide: [
      'Shopify store setup & design',
      'Payment & shipping integration',
      'SEO optimization for products',
      'Marketing automation setup',
      'Sales funnel creation',
    ],
    tags: ['E-Commerce', 'Shopify', 'SEO', 'Marketing', 'Sales Funnel', 'Store Setup'],
    whyWorkWithMe: [
      'End-to-end e-commerce expertise',
      'High-converting store layouts',
      'Proven marketing strategies',
      'Ongoing store management options',
      'Strong focus on increasing sales',
    ],
  },
];
