
import type { Service } from './data';

export const services: Service[] = [
  {
    title: 'UI/UX Design',
    shortBio: 'Modern, user-focused mobile app and website design with seamless usability.',
    price: '₹10,000 (full project)',
    icon: "🎨",
    tool: "Figma",
    bgColor: "bg-blue-100",
    whatIProvide: [
      'Mobile app design',
      'Website UI design',
      'Prototyping and wireframes',
      'Responsive layouts',
      'Design system creation',
    ],
    tags: ['UI Design', 'UX Design', 'Mobile Apps', 'Websites', 'Prototypes', 'Wireframes'],
    whyWorkWithMe: [
      'User-first approach',
      'Fast turnaround',
      'Modern, trend-aligned designs',
      'Proven track record with startups and businesses',
      'Clear communication',
    ],
  },
  {
    title: 'UX Strategy',
    shortBio: 'Research, redesign, and consulting to improve product usability and conversions.',
    price: 'Custom pricing',
    icon: "✏️",
    tool: "Research",
    bgColor: "bg-yellow-100",
    whatIProvide: [
      'UX audits & usability testing',
      'Customer journey mapping',
      'Redesign recommendations',
      'Conversion rate optimization',
      'Accessibility improvements',
    ],
    tags: ['UX Research', 'Usability', 'CRO', 'User Testing', 'Redesign', 'Strategy'],
    whyWorkWithMe: [
      'Data-driven decision-making',
      'Industry-proven UX methods',
      'Tailored strategies for your target audience',
      'Long-term growth focus',
      'Hands-on collaboration',
    ],
  },
  {
    title: 'SEO & Marketing',
    shortBio: 'Creative SEO and digital marketing for strong online presence.',
    price: 'Custom pricing',
    icon: "📈",
    tool: "Marketing",
    bgColor: "bg-purple-100",
    whatIProvide: [
      'On-page & technical SEO',
      'Keyword research',
      'Blog & content optimization',
      'Social media strategy',
      'Ad campaign setup & optimization',
    ],
    tags: ['SEO', 'Digital Marketing', 'Keywords', 'Google Ads', 'Social Media', 'Content Marketing'],
    whyWorkWithMe: [
      'White-hat SEO practices',
      'Measurable marketing results',
      'Custom strategies for your niche',
      'Latest marketing tools & trends',
      'End-to-end digital growth approach',
    ],
  },
  {
    title: 'Web Development Services',
    shortBio: `**Industry-Specific Market Pricing (India – 2025)**
- Static Landing Page: ₹3,000 – ₹8,000 (2–4 Days)
- Business Portfolio Site: ₹7,000 – ₹15,000 (4–7 Days)
- Dynamic Website: ₹15,000 – ₹35,000 (1–2 Weeks)`,
    price: 'From ₹3,000',
    icon: "💻",
    tool: "Webflow",
    bgColor: "bg-pink-100",
    whatIProvide: [
      'Custom Websites – Modern, responsive, and SEO-friendly designs.',
      'Landing Pages – High-converting layouts for campaigns & ads.',
      'Frontend Development – Pixel-perfect UI with smooth animations.',
      'Dynamic Websites – Content-driven, user-interactive, and trend-focused.',
      'Portfolio & Business Sites – Professional presence for personal branding or companies.',
    ],
    tags: ['WebDevelopment', 'LandingPageDesign', 'FrontendDeveloper', 'DynamicWebsite', 'ResponsiveDesign', 'SEO', 'CustomWebSolutions', 'IndiaWebDesign2025'],
    whyWorkWithMe: [
      'Pixel-Perfect Design – Every element crafted with attention to detail.',
      'Fast Loading & Mobile Friendly – Optimized for all devices.',
      'Market-Tuned Strategies – Designs that match 2025’s trends and user expectations.',
      'Affordable & Transparent Pricing – No hidden charges, clear deliverables.',
    ],
  },
  {
    title: 'Content & Branding',
    shortBio: 'AI-assisted content creation to strengthen brand and engage audiences.',
    price: 'Per content',
    icon: '✍️',
    tool: 'Content',
    bgColor: 'bg-green-100',
    whatIProvide: [
      'Brand voice & identity setup',
      'AI-generated blog & article writing',
      'Social media content creation',
      'Copywriting for ads & websites',
      'Content calendar planning',
    ],
    tags: ['Content Writing', 'Branding', 'Copywriting', 'Social Media', 'Marketing', 'AI Content'],
    whyWorkWithMe: [
      'Creative storytelling with AI precision',
      'Consistent, brand-aligned content',
      'Engaging and SEO-optimized writing',
      'Experienced in multiple industries',
      'On-time content delivery',
    ],
  },
  {
    title: 'E-Commerce Solutions',
    shortBio: 'Shopify stores with admin, SEO, marketing, and sales optimization.',
    price: 'Custom pricing',
    icon: '🛒',
    tool: 'Shopify',
    bgColor: 'bg-orange-100',
    whatIProvide: [
      'Shopify store setup & design',
      'Payment & shipping integration',
      'SEO optimization for products',
      'Marketing automation setup',
      'Sales funnel creation',
    ],
    tags: ['E-Commerce', 'Shopify', 'SEO', 'Marketing', 'Sales Funnel', 'Store Setup'],
    whyWorkWithMe: [
      'End-to-end e-commerce expertise',
      'High-converting store layouts',
      'Proven marketing strategies',
      'Ongoing store management options',
      'Strong focus on increasing sales',
    ],
  },
];
